### ISSUE TITLE
Base File.sublime-settings conflict

### ISSUE THREAD

**Issue by mattst** [ehuss/Sublime-Wrap-Plus#49]
The use of `Base File.sublime-settings` conflicts with both the [Alignment](https://packagecontrol.io/packages/Alignment) and [DocBlockr](https://packagecontrol.io/packages/DocBlockr) packages and probably several others.

I suspect the problem has arisen because the plugin developers misunderstood [this documentation page](http://sublimetext.info/docs/en/customization/settings.html), which is far from clear, and did not realize that `Base File.sublime-settings` is an example which should be replaced by `Package Name.sublime-settings`.

I have to use `User/Base File.sublime-settings` for both my *Alignment* and *Wrap Plus* settings instead of being able to use `User/Alignment.sublime-settings` and `User/Wrap Plus.sublime-settings` which is what the design for the Sublime Text settings system intended.

Hope this helps.

P.S. Thanks for the excellent plugin, v. useful.

**Comment by ehuss** [comment]
Why do you think it is a conflict?  "Base File" is a global definition file, it is used on purpose.  The reason for doing it this way is because it gives you the flexibility to define these settings per-syntax and per-project.  If you want to define these settings globally, it probably makes more sense to put them in User/Preferences.sublime-setings.  For your reference, you can put them in any of the following:

1. User/Preferences.sublime-settings
2. Project Settings
3. User/&lt;syntax&gt;.sublime-settings
4. User/Distraction Free.sublime-settings
